---
# openstack router unset --external-gateway  TEST-ROUTER
# ^^^ allows gateway subnet to be deleted

# Get router list
# For each router
#   openstack router unset --external-gateway router
#   openstack router remove subnet router <subnet0>...<subnetn>
#   openstack router delete router
# Get subnet list
# For each subnet
#   openstack subnet delete subnet
# Get network list
# For each network
#   openstack network delete network

####################  Begin Remove Routers  #####################
- name: Get router list
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router list -f value -c ID'
  register: output

- name: Set router list fact
  set_fact:
    router_list_output: "{{ output.stdout_lines }}"

- name: Unset external-gateway on router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router unset --external-gateway "{{ item }}"'
  with_items: "{{ router_list_output }}"

- name: Get router details
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router show -f json "{{ item }}"'
  register: output
  with_items: "{{ router_list_output }}"

- name: Set router details fact
  set_fact:
    router_details_output: "{{ output.results }}"

- name: Remove subnets from routers
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router remove subnet {{ (item.stdout | from_json).id }} {{ (item.stdout | from_json).interfaces_info | from_json | json_query("[*].subnet_id") | join(" ") }}'
  when:  '(item.stdout | from_json).interfaces_info | from_json | json_query("[*].subnet_id") | join(" ")'
  with_items: "{{ router_details_output }}"

- name: Delete router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router delete "{{ item }}"'
  with_list: "{{ router_list_output }}"
####################  End Remove Routers    #####################

####################  Begin Remove Subnets  #####################
- name: Get subnets
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack subnet list -f value -c ID'
  register: output

- name: Set subnet list fact
  set_fact:
    subnet_list_output: "{{ output.stdout_lines }}"

- name: Delete subnets
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack subnet delete "{{ item }}"'
  with_items: "{{ subnet_list_output }}"
####################  End Remove Subnets    #####################

####################  Begin Remove Networks #####################
- name: Get networks
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack network list -f value -c ID'
  register: output

- name: Set network list fact
  set_fact:
    network_list_output: "{{ output.stdout_lines }}"

- name: Delete networks
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack network delete "{{ item }}"'
  with_items: "{{ network_list_output }}"
####################  End Remove Networks   #####################
