---
- name: Check for image in glance
  shell: |
    lxc-attach -n {{ utility_container.stdout }}  \
    -- bash -c '. /root/openrc ; \
    openstack image list | grep "{{ image.name }}"'
  register: glance_image
  changed_when: false
  failed_when: false

- name: Download system image file
  get_url:
    url: "{{ image.url }}"
    dest: "/var/lib/lxc/{{ utility_container.stdout }}/rootfs/tmp/os_image_{{ image.name }}"
    timeout: 600   # big files might take a while to download
  when: glance_image.rc == 1

- name: Install system image
  shell: |
    lxc-attach -n {{ utility_container.stdout }} \
    -- bash -c '. /root/openrc ; \
    openstack image create \
    --public \
    --disk-format "{{ image.format }}" \
    --file "/tmp/os_image_{{ image.name }}" \
    "{{ image.name }}"'
  when: glance_image.rc == 1

- name: Clean up temp file
  file:
    path: "/var/lib/lxc/{{ utility_container.stdout }}/rootfs/tmp/os_image_{{ image.name }}"
    state: absent
