---
- name: Copy the rpc_maas var file
  copy:
    src: "/opt/rpc-openstack/etc/openstack_deploy/user_rpco_maas_variables.yml.example"
    dest: "/etc/openstack_deploy/user_rpco_maas_variables.yml"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Clean old rpc-maas dir if previously existing
  file:
    state: absent
    path: /opt/rpc-maas

- name: Clone rpc-maas repo
  git:
    repo=https://github.com/rcbops/rpc-maas.git
    dest=/opt/rpc-maas

- name: Set the rpc_maas vars
  shell: |
    cd /opt/rpc-maas/playbooks
    sed -i 's|^# influx_telegraf_targets|influx_telegraf_targets|g' /etc/openstack_deploy/user_rpco_maas_variables.yml
    openstack-ansible -e maas_pre_flight_metadata_check_enabled=false site.yml
  changed_when: false
  failed_when: false
