---
- name: Copy the rpc_maas var file
  copy:
    src: "/opt/rpc-openstack/etc/openstack_deploy/user_rpco_maas_variables.yml.example"
    dest: "/etc/openstack_deploy/user_rpco_maas_variables.yml"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Clean old rpc-maas dir if previously existing
  file:
    state: absent
    path: /opt/rpc-maas

- name: Clone rpc-maas repo
  git:
    repo=https://github.com/rcbops/rpc-maas.git
    dest=/opt/rpc-maas

- name: Maas credentials setup
  shell: sed -e '/^\(#\|-\|$\)/d' /opt/rpc-maas/tests/user_rpcm_secrets.yml >> /etc/openstack_deploy/user_secrets.yml

- name: Set the rpc_maas vars
  shell: |
    cd /opt/rpc-maas/playbooks
    sed -i 's|^# influx_telegraf_targets|influx_telegraf_targets|g' /etc/openstack_deploy/user_rpco_maas_variables.yml
    date
    openstack-ansible -e maas_pre_flight_metadata_check_enabled=false site.yml -vvv
    date
  async: 3600
  poll: 30
  changed_when: false
  failed_when: false

- name: Run maas-verify-local
  shell: |
    cd /opt/rpc-maas/playbooks
    date
    openstack-ansible maas-verify.yml --tags "maas-verify-local" -vvv
    date
  async: 7200
  poll: 30
  changed_when: false
  failed_when: false
  register: run_maas_verify_local
