---
- name: Copy the rpc_maas var file
  copy:
    src: "/opt/rpc-openstack/etc/openstack_deploy/user_rpco_maas_variables.yml.example"
    dest: "/etc/openstack_deploy/user_rpco_maas_variables.yml"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Clean old rpc-maas dir if previously existing
  file:
    state: absent
    path: /opt/rpc-maas

- name: Clone rpc-maas repo
  git:
    repo=https://github.com/rcbops/rpc-maas.git
    dest=/opt/rpc-maas

- name: Maas credentials setup
  shell: |
    echo 'maas_rabbitmq_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'maas_keystone_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'maas_rally_users_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'maas_rally_galera_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'maas_swift_accesscheck_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'influxdb_db_root_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'influxdb_db_metric_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'grafana_db_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml
    echo 'grafana_admin_password: secrete' | tee -a /etc/openstack_deploy/user_secrets.yml

- name: Set the rpc_maas vars
  shell: |
    cd /opt/rpc-maas/playbooks
    sed -i 's|^# influx_telegraf_targets|influx_telegraf_targets|g' /etc/openstack_deploy/user_rpco_maas_variables.yml
    openstack-ansible -e maas_pre_flight_metadata_check_enabled=false site.yml
  changed_when: false
  failed_when: false

- name: Debug Maas playbook content
  shell: tail -n +1 /etc/openstack_deploy/*.yml
