---
- name: Create test network
  os_network:
    cloud: default
    state: present
    name: "{{ test_resources.network }}"
    external: false
  delegate_to: localhost

- name: Create test subnet
  os_subnet:
    cloud: default
    state: present
    network_name: "{{ test_resources.network }}"
    name: "{{ test_resources.subnet }}"
    cidr: 192.168.1.0/24
    allocation_pool_start: 192.168.1.2
    allocation_pool_end: 192.168.1.254
    gateway_ip: 192.168.1.1
  delegate_to: localhost

- name: Create test router
  os_router:
    cloud: default
    state: present
    name: "{{ test_resources.router }}"
    network: "{{ gateway_network }}"
    interfaces:
      - "{{ test_resources.subnet }}"
  delegate_to: localhost
