---
# openstack router unset --external-gateway  TEST-ROUTER
# ^^^ allows gateway subnet to be deleted

- name: Check for gateway network
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack network list | grep "{{ gateway_network }}"'

- name: Check for test subnet
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack subnet list | grep "{{ test_subnet }}"'
  register: test_subnet_instance
  changed_when: false
  failed_when: false

- name: Check for test router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router list | grep "{{ test_router }}"'
  register: test_router_instance
  changed_when: false
  failed_when: false

- name: Unset gateway on test router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router unset --external-gateway "{{ test_router }}"'
  when:
    - test_router_instance.rc == 0

- name: Remove test subnet from router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router remove subnet "{{ test_router }}" "{{ test_subnet }}"'
  failed_when: false
  when:
    - test_router_instance.rc == 0
    - test_subnet_instance.rc == 0

- name: Delete test router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack router delete "{{ test_router }}"'
  when:
    - test_router_instance.rc == 0

- name: Delete test subnet
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack subnet delete "{{ test_subnet }}"'
  when:
    - test_subnet_instance.rc == 0

- name: Check for test network
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack network list | grep "{{ test_network }}"'
  register: test_network_instance
  changed_when: false
  failed_when: false

- name: Delete test network
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}"  \
    -- bash -c '. /root/openrc ; \
    openstack network delete "{{ test_network }}"'
  when:
    - test_network_instance.rc == 0

- name: Create test network
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}" \
    -- bash -c '. /root/openrc ; \
    openstack network create \
    -f json \
    "{{ test_network }}"'

- name: Create test subnet
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}" \
    -- bash -c '. /root/openrc ; \
    openstack subnet create \
    --allocation-pool start=192.168.1.2,end=192.168.1.254 \
    --host-route destination=0.0.0.0/0,gateway=192.168.1.1 \
    --subnet-range 192.168.1.0/24 \
    --network "{{ test_network }}" \
    "{{ test_subnet }}"'

- name: Create test router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}" \
    -- bash -c '. /root/openrc ; \
    openstack router create \
    "{{ test_router }}"'

- name: Add subnet to router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}" \
    -- bash -c '. /root/openrc ; \
    openstack router add subnet "{{ test_router }}" "{{ test_subnet }}"'

- name: Set external gateway on router
  shell: |
    lxc-attach -n "{{ utility_container.stdout }}" \
    -- bash -c '. /root/openrc ; \
    openstack router set --external-gateway "{{ gateway_network }}" "{{ test_router }}"'
