---
- name: Create test network
  os_network:
    cloud: default
    state: present
    name: "{{ test_network }}"
    external: False
  delegate_to: "{{ cli_host }}"

- name: Create test subnet
  os_subnet:
    cloud: default
    state: present
    network_name: "{{ test_network }}"
    name: "{{ test_subnet }}"
    cidr: 192.168.1.0/24
    allocation_pool_start: 192.168.1.2
    allocation_pool_end: 192.168.1.254
    gateway_ip:  192.168.1.1
  delegate_to: "{{ cli_host }}"

- name: Create test router
  os_router:
    cloud: default
    state: present
    name: "{{ test_router }}"
    network: "{{ provider_net_name }}"
    interfaces:
      - "{{ test_subnet }}"
  delegate_to: "{{ cli_host }}"
