---
# Task file for locating the 'clouds.yaml' file and placing it on the deployment host and infra1 host.


- name: Extract '{{ os_version_file_path }}' Version File Contents from 'infra1' Host
  slurp:
    src: "{{ os_version_file_path }}"
  register: os_version_file_contents


- name: Create '{{ os_version_ini_path }}' Version File on Deployment Host
  copy:
    content: "{{ os_version_file_contents.content | b64decode }}"
    dest: "{{ os_version_ini_path }}"
  delegate_to: localhost

- name: Modify '{{ os_version_ini_path }}' Version File on Deployment Host with Default Section Header
  lineinfile:
    path: "{{ os_version_ini_path }}"
    line: "[default]"
    insertbefore: BOF
  delegate_to: localhost
