---
- name: Ensure rpc_support security group
  os_security_group:
    cloud: default
    state: present
    name: rpc-support
  delegate_to: localhost

- name: Ensure rpc_support security group rules tcp
  os_security_group_rule:
    cloud: default
    security_group: rpc-support
    state: present
    direction: ingress
    protocol: tcp
    port_range_min: "{{ item }}"
    port_range_max: "{{ item }}"
  with_items:
    - 22
    - 3389
  delegate_to: localhost

- name: Ensure rpc_support security group rules icmp
  os_security_group_rule:
    cloud: default
    security_group: rpc-support
    state: present
    direction: ingress
    protocol: icmp
  delegate_to: localhost
