---
- name: Register servers
  os_server_facts:
    cloud: default
    server: '*'
  register: openstack_servers

- name: Show the value of openstack_servers
  debug:
    var: openstack_servers

- name: Delete all servers
  os_server:
    cloud: default
    state: absent
    name: "{{ item.name }}"
  with_items: "{{ openstack_servers }}"
  delegate_to: "{{ cli_host }}"
