---
- name: Set the rpc-openstack variables
  set_fact:
    rpc_openstack: "{{ ansible_local['rpc_openstack']['rpc_product'] }}"
  when:
    - ansible_local.rpc_openstack is defined
    - ansible_local.rpc_openstack.rpc_product is defined

- name: Set the rpc-release variable
  set_fact:
    rpc_product_release: "{{ rpc_openstack['rpc_product_release'] }}"
  when:
    - rpc_openstack is defined
    - rpc_openstack['rpc_product_release'] is defined
    - rpc_product_release is undefined or
      rpc_product_release == 'undefined'

- name: Set the rpc-release variable from environment
  set_fact:
    rpc_product_release: "{{ lookup('env', 'RPC_PRODUCT_RELEASE') }}"
  when:
    - rpc_openstack is undefined or
      rpc_openstack['rpc_product_release'] is undefined

- name: Find the proper inventory file rpc-o
  shell: find /etc/openstack_deploy -name openstack_inventory.py -print
  register: find_inventory_file
  ignore_errors: true
  when:
    - rpc_openstack is defined
  delegate_to: localhost

- name: Find the proper inventory file osp-mnaio
  shell: find /opt -name hosts -print
  register: find_inventory_file
  ignore_errors: true
  when:
    - rpc_openstack is undefined
  delegate_to: localhost

- name: Copy inventory to working file
  copy:
    src: "{{ find_inventory_file.stdout }}"
    dest: "{{ working_inventory }}"

- name: Set proper inventory file
  set_fact:
    inventory_file: "{{ working_inventory }}"

- name: Register utility_container
  shell: |
    lxc-ls -1 | grep utility | head -n 1
  register: utility_container
  when:
    - rpc_openstack is defined

- name: Set cli_host
  set_fact:
    cli_host: "{{ ansible_hostname }}"
    #cli_host: "{{ utility_container if utility_container is defined else ansible_hostname }}"
