---
- name: Ensure path for ansible custom facts
  file:
    state: directory
    recurse: true
    path: "{{ custom_fact_path }}"

- name: Ensure file for ansible custom facts
  file:
    state: touch
    path: "{{ custom_fact_path }}/system_tests.fact"

- name: Set the rpc-openstack variables
  set_fact:
    rpc_openstack: "{{ ansible_local['rpc_openstack']['rpc_product'] }}"
  when:
    - ansible_local.rpc_openstack is defined
    - ansible_local.rpc_openstack.rpc_product is defined

- name: Set the rpc-release variable
  set_fact:
    rpc_product_release: "{{ rpc_openstack['rpc_product_release'] }}"
  when:
    - rpc_openstack is defined
    - rpc_openstack['rpc_product_release'] is defined
    - rpc_product_release is undefined or
      rpc_product_release == 'undefined'

- name: Set the rpc-release variable from environment
  set_fact:
    rpc_product_release: "{{ lookup('env', 'RPC_PRODUCT_RELEASE') }}"
  when:
    - rpc_openstack is undefined or
      rpc_openstack['rpc_product_release'] is undefined

- name: Create custom fact for rpc_product_release
  copy:
    content: "{{ {'rpc_product_release':rpc_product_release} | to_nice_json(indent=2) }}"
    dest: "{{ custom_fact_path }}/system_tests.fact"

- name: Find the proper inventory file
  shell: find /opt/openstack-ansible -name dynamic_inventory.py -print
  register: find_inventory_file
  ignore_errors: true

- name: Set proper inventory file
  set_fact:
    inventory_file: "{{ find_inventory_file.stdout }}"

- name: Register utility container
  shell: |
    lxc-ls -1 | grep utility | head -n 1
  register: utility_container

- name: Register galera container
  shell: |
    lxc-ls -1 | grep galera | head -n 1
  register: galera_container
