---
- name: Check for key file
  stat:
    path: /root/.ssh/rpc_support
  changed_when: false
  failed_when: false
  register: support_key_check

- name: Create support SSH key
  command: |
    ssh-keygen -f "/root/.ssh/rpc_support" -t rsa -q -N ""
  register: support_key_create
  changed_when: support_key_create.rc == 0
  failed_when: support_key_create.rc >= 1
  when: not support_key_check.stat.exists |bool

- name: Get contents of support SSH key
  slurp:
    src: "/root/.ssh/rpc_support"
  register: support_key
  when: support_key_check.stat.exists |bool or support_key_create|changed

- name: Get contents of support SSH pub key
  slurp:
    src: "/root/.ssh/rpc_support.pub"
  register: support_pub_key
  when: support_key_check.stat.exists |bool or support_key_create|changed

- name: Get fingerprint of rpc_support SSH key
  shell: |
    ssh-keygen -lf /root/.ssh/rpc_support.pub |awk '/(RSA|DSA)/ {print $2}'
  register: support_key_fingerprint
  changed_when: support_key_fingerprint.rc == 0
  failed_when: false
  when: support_key_check.stat.exists |bool or support_key_create|changed

- name: Check for support keypair in nova
  shell: |
    . /root/openrc
    {{ ops_pip_venv_enabled | bool | ternary(ops_venv, omit) }}/bin/nova keypair-list | grep rpc_support
  register: nova_support_key
  changed_when: false
  failed_when: false

- name: Delete support keypair in nova
  shell: |
    . /root/openrc
    {{ ops_pip_venv_enabled | bool | ternary(ops_venv, omit) }}/bin/nova keypair-delete rpc_support
  register: nova_support_key_delete
  changed_when: nova_support_key_delete.rc == 0
  failed_when: false
  retries: 2
  delay: 10
  when: nova_support_key.rc == 0 and support_key_fingerprint.stdout not in nova_support_key.stdout

- name: Add support key to nova
  shell: |
    . /root/openrc
    {{ ops_pip_venv_enabled | bool | ternary(ops_venv, omit) }}/bin/nova keypair-add --pub-key /root/.ssh/rpc_support.pub rpc_support
  retries: 2
  delay: 10
  when: nova_support_key_delete|changed or nova_support_key.rc == 1
  vars_files:
    - "vars/main.yml"
