---
- name: Install packages required for RPC support
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 600
    force: true
  with_items: "{{ ops_apt_util_packages }}"
  when:
    - ansible_os_family == 'Debian'
  register: support_package_installs
  until: support_package_installs is success
  retries: 2
  delay: 10

- name: Install host packages required for RPC support
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 600
  with_items: "{{ ops_apt_host_packages }}"
  when:
    - ansible_virtualization_role == 'host'
    - ansible_os_family == 'Debian'
- name: Check for key file
  stat:
    path: /root/.ssh/rpc_support
  changed_when: false
  failed_when: false
  register: support_key_check

- name: Create support SSH key
  command: |
    ssh-keygen -f "/root/.ssh/rpc_support" -t rsa -q -N ""
  register: support_key_create
  changed_when: support_key_create.rc == 0
  failed_when: support_key_create.rc >= 1
  when: not support_key_check.stat.exists |bool

- name: Get contents of support SSH key
  slurp:
    src: "/root/.ssh/rpc_support"
  register: support_key
  when: support_key_check.stat.exists |bool or support_key_create is changed

- name: Get contents of support SSH pub key
  slurp:
    src: "/root/.ssh/rpc_support.pub"
  register: support_pub_key
  when: support_key_check.stat.exists |bool or support_key_create is changed

- name: Get fingerprint of rpc_support SSH key
  shell: |
    ssh-keygen -lf /root/.ssh/rpc_support.pub |awk '/(RSA|DSA)/ {print $2}'
  register: support_key_fingerprint
  changed_when: support_key_fingerprint.rc == 0
  failed_when: false
  when: support_key_check.stat.exists |bool or support_key_create is changed

- name: Get container rootfs directory list
  shell: "ls -1 -d /var/lib/lxc/*/rootfs"
  register: container_rootfs_list

- name: Distribute support SSH private key to containers
  copy:
    dest: "{{ item }}/root/.ssh/rpc_support"
    content: "{{ support_key.content | b64decode }}"
    owner: "root"
    group: "root"
    mode: "0600"
  with_items: "{{ container_rootfs_list.stdout_lines }}"
  when:
    - support_key.content |default('') |length > 64

- name: Distribute support SSH public key to containers
  copy:
    dest: "{{ item }}/root/.ssh/rpc_support.pub"
    content: "{{ support_pub_key.content | b64decode }}"
    owner: "root"
    group: "root"
    mode: "0600"
  with_items: "{{ container_rootfs_list.stdout_lines }}"
  when:
    - support_pub_key.content |default('') |length > 64

- name: Distribute support SSH private key to deployment host
  copy:
    dest: "/root/.ssh/rpc_support"
    content: "{{ support_key.content | b64decode }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when:
    - support_key.content |default('') |length > 64
  delegate_to: localhost

- name: Distribute support SSH public key to deployment host
  copy:
    dest: "/root/.ssh/rpc_support.pub"
    content: "{{ support_pub_key.content | b64decode }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when:
    - support_pub_key.content |default('') |length > 64
  delegate_to: localhost

- name: Add support key to nova
  os_keypair:
    cloud: default
    state: present
    name: rpc_support
    public_key: "{{ support_pub_key.content | b64decode }}"
  when:
    - support_pub_key.content |default('') |length > 64
  delegate_to: localhost
